services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: patcornejo
      MONGO_INITDB_ROOT_PASSWORD: sroa
    volumes:
      - ./db_data/:/data/db/
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data